[package]
name = "flox-rust-testing"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
